### PR TITLE
Add scrollbar to Output

### PR DESCRIPTION
**Pull request by CableSynth**
Add starting scrollbar to output. 
Change some instances of `&App` to `&mut App`

### CODE REVIEW

**Comment by CableSynth** [comment]
Edit: Might handle #20

**Comment by CableSynth** [comment]
see if you like this this scrollbar @wcampbell0x2a not sure if there was a specific way you wanted it.

**Comment by wcampbell0x2a** [comment]
Thanks! please rebase into a single commit.

**Comment by CableSynth** [comment]
Mb will do.

**Comment by CableSynth** [comment]
Closing cause I'm bad

**Pull request closed without merging**
